// SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
//
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

package common

type EventType uint8

// Events between Profile and SimUe
const (
	PROFILE_START_EVENT EventType = 1 + iota
	PROFILE_PASS_EVENT
	PROFILE_FAIL_EVENT
)

// Events between UE and GNodeB (UU)
const (
	CONNECT_REQUEST_EVENT EventType = 1 + iota
	UL_INFO_TRANSFER_EVENT
	DL_INFO_TRANSFER_EVENT
	DATA_BEARER_SETUP_REQUEST_EVENT
	DATA_BEARER_SETUP_RESPONSE_EVENT
)

// Events betweem UE and AMF (N1)

// Following events are numbered same as the NAS Message types in section 9.7 of
// 3GPP TS 24.501

const UE_5GS_MOBILITY_MANAGEMENT_EVENTS EventType = 64
const UE_5GS_SESSION_MANAGEMENT_EVENTS EventType = 192

// 5GS Mobility Management events.
const (
	_ EventType = UE_5GS_MOBILITY_MANAGEMENT_EVENTS + iota

	REG_REQUEST_EVENT //65
	REG_ACCEPT_EVENT
	REG_COMPLETE_EVENT
	REG_REJECT_EVENT
	DEREG_REQUEST_UE_ORIG_EVENT
	DEREG_ACCEPT_UE_ORIG_EVENT
	DEREG_REQUEST_UE_TERM_EVENT
	DEREG_ACCEPT_UE_TERM_EVENT //72

	SERVICE_REQUEST_EVENT = UE_5GS_MOBILITY_MANAGEMENT_EVENTS + 3 + iota //76
	SERVICE_REJECT_EVENT
	SERVICE_ACCEPT_EVENT //78

	AUTH_REQUEST_EVENT = UE_5GS_MOBILITY_MANAGEMENT_EVENTS + 10 + iota //86
	AUTH_RESPONSE_EVENT
	AUTH_REJECT_EVENT
	AUTH_FAILURE_EVENT
	AUTH_RESULT_EVENT
	ID_REQUEST_EVENT
	ID_RESPONSE_EVENT
	SEC_MOD_COMMAND_EVENT
	SEC_MOD_COMPLETE_EVENT
	SEC_MOD_REJECT_EVENT //95

	FIVE_GMM_STATUS_EVENT = UE_5GS_MOBILITY_MANAGEMENT_EVENTS + 14 + iota //86
	NOTIFICATION_EVENT
	NOTIFICATION_RESPONSE_EVENT
	UL_NAS_TRANSPORT_EVENT
	DL_NAS_TRANSPORT_EVENT
)

// 5GS Session Management events.
const (
	_ EventType = UE_5GS_SESSION_MANAGEMENT_EVENTS + iota

	PDU_SESS_EST_REQUEST_EVENT //193
	PDU_SESS_EST_ACCEPT_EVENT
	PDU_SESS_EST_REJECT_EVENT

	PDU_SESS_AUTH_COMMAND_EVENT = UE_5GS_SESSION_MANAGEMENT_EVENTS + 1 + iota
	PDU_SESS_AUTH_COMPLETE_EVENT
	PDU_SESS_AUTH_RESULT_EVENT

	PDU_SESS_MOD_REQUEST_EVENT = UE_5GS_SESSION_MANAGEMENT_EVENTS + 2 + iota
	PDU_SESS_MOD_REJECT_EVENT
	PDU_SESS_MOD_COMMAND_EVENT
	PDU_SESS_MOD_COMPLETE_EVENT
	PDU_SESS_MOD_CMD_REJECT_EVENT

	PDU_SESS_REL_REQUEST_EVENT = UE_5GS_SESSION_MANAGEMENT_EVENTS + 5 + iota
	PDU_SESS_REL_REJECT_EVENT
	PDU_SESS_REL_COMMAND_EVENT
	PDU_SESS_REL_COMPLETE_EVENT

	FIVEGSM_STATUS_EVENT = UE_5GS_SESSION_MANAGEMENT_EVENTS + 6 + iota
)

// Events between GNodeB and AMF (N2)
const (
	DOWNLINK_NAS_TRANSPORT_EVENT EventType = 1 + iota
	INITIAL_CONTEXT_SETUP_REQUEST_EVENT
	PDU_SESS_RESOURCE_SETUP_REQUEST_EVENT
)
