# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 Intel Corporation
name: Pull Request

on: [pull_request]

concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true
  

jobs:
  build:
    #env:
      # DOCKER_REGISTRY: "docker.io/"
      # DOCKER_REPOSITORY: "badhrinathpa/"
      # VERSION: "PR-${{ github.event.pull_request.number }}"
    runs-on: ubuntu-latest
    steps:
      # Checkout and build
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          make docker-build
      # Format the code
      - name: Go Format
        run: |
          make fmt

      - name: Show all CI changes
        run: |
          git --no-pager diff

      # Build again and commit
      - name: Build Docker image after format
        run: |
          make docker-build
      - name: Update PR with changes
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            Updated with changes from CI
          branch: ${{ github.event.pull_request.head.ref }}
          author: "Github Actions <actions@github>"
          commit-message: "Actions: Updated with changes from CI"
